/**
 * 课程与营期域 — 课程子域 Sim 种子数据
 * 来源：PRD 18-课程与营期域 §12 ENT-COURSE-001~008
 * 对齐 SugarMate courseStore mock + 适配 D2/D9/D14/D16/D35
 * ID 打通：COURSE-202608-00001 / LESSON-202608-00001 / LECT-202608-00001
 */

import type {
  Course, Lesson, QuestionBank, Question, AnswerRecord,
  CourseQuizConfig, CourseReview, CourseReviewReply,
} from '../../contracts/schemas/course-schemas';
import type { Lecturer } from '../../contracts/schemas/lecturer-schemas';

const now = Math.floor(Date.now() / 1000);
const dayAgo = (n: number) => now - n * 86400;

// ── 课程（ENT-COURSE-001，15门课程·D2分类通用化·D35红包配置）──
export const SEED_COURSES: Course[] = [
  {
    id: 'COURSE-202608-00001',
    course_no: 'COURSE-202608-00001',
    title: '高效学习方法论',
    description: '系统讲解高效学习的基础知识、工具使用、时间管理等',
    cover_url: '',
    category_id: 'cat-001',
    category_name: '通识教育',
    sub_category: '学习入门',
    tags: ['学习', '工具', '方法论'],
    lecturer_id: 'LECT-202608-00001',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 2700,
    price: 9900,  // 分·D9
    is_paid: true,
    lesson_count: 5,
    published_lesson_count: 5,
    camp_ref_count: 2,
    question_bank_id: 'QB-202608-00001',
    quiz_config_id: 'QUIZCFG-202608-00001',
    total_learners: 1234,
    total_learning_minutes: 18510,
    rating: 4.8,
    review_count: 56,
    status: 'published',
    review_remark: undefined,
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(10),
    completion_reward_enabled: true,
    answer_reward_enabled: true,
    reward_type: 'red_packet_rule',
    reward_amount: 100,  // 分
    red_packet_rule_id: 'R-00001',
    created_at: dayAgo(15),
    updated_at: dayAgo(10),
  },
  {
    id: 'COURSE-202608-00002',
    course_no: 'COURSE-202608-00002',
    title: '职场沟通技巧',
    description: '职场沟通基础知识，科学表达与高效协作',
    cover_url: '',
    category_id: 'cat-003',
    category_name: '职业技能',
    sub_category: '沟通基础',
    tags: ['沟通', '职场', '表达'],
    lecturer_id: 'LECT-202608-00002',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 1800,
    price: 0,
    is_paid: false,
    lesson_count: 3,
    published_lesson_count: 3,
    camp_ref_count: 1,
    question_bank_id: 'QB-202608-00002',
    quiz_config_id: 'QUIZCFG-202608-00002',
    total_learners: 567,
    total_learning_minutes: 8505,
    rating: 4.6,
    review_count: 23,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(7),
    completion_reward_enabled: false,
    answer_reward_enabled: true,
    reward_type: 'points',
    reward_amount: 10,
    red_packet_rule_id: null,
    created_at: dayAgo(12),
    updated_at: dayAgo(7),
  },
  {
    id: 'COURSE-202608-00003',
    course_no: 'COURSE-202608-00003',
    title: '运动健康指南',
    description: '科学运动方案与注意事项',
    cover_url: '',
    category_id: 'cat-005',
    category_name: '健康管理',
    tags: ['运动', '健康'],
    lecturer_id: 'LECT-202608-00001',    lecturer_role_type: '资深讲师',
    source: 'live_replay',
    source_live_session_id: 'LS-202608-001',
    mode: 'recorded',
    visibility: 'camp_only',
    total_video_duration: 3600,
    price: 19900,
    is_paid: true,
    lesson_count: 8,
    published_lesson_count: 8,
    camp_ref_count: 1,
    question_bank_id: 'QB-202608-00003',
    quiz_config_id: null,
    total_learners: 89,
    total_learning_minutes: 3204,
    rating: 4.9,
    review_count: 12,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(5),
    completion_reward_enabled: true,
    answer_reward_enabled: false,
    reward_type: 'red_packet_rule',
    reward_amount: 200,
    red_packet_rule_id: 'R-00002',
    created_at: dayAgo(8),
    updated_at: dayAgo(5),
  },
  {
    id: 'COURSE-202608-00004',
    course_no: 'COURSE-202608-00004',
    title: '商业思维直播课',
    description: '直播形式讲解商业思维与创业实战',
    cover_url: '',
    category_id: 'cat-006',
    category_name: '商业管理',
    tags: ['商业', '思维', '直播'],
    lecturer_id: 'LECT-202608-00002',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'live',
    visibility: 'public',
    total_video_duration: 0,
    price: 29900,
    is_paid: true,
    lesson_count: 4,
    published_lesson_count: 4,
    camp_ref_count: 0,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 256,
    total_learning_minutes: 0,
    rating: 4.7,
    review_count: 18,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(3),
    completion_reward_enabled: false,
    answer_reward_enabled: false,
    reward_type: 'points',
    reward_amount: 0,
    red_packet_rule_id: null,
    created_at: dayAgo(5),
    updated_at: dayAgo(2),
  },
  {
    id: 'COURSE-202608-00005',
    course_no: 'COURSE-202608-00005',
    title: '数据分析入门',
    description: '从零开始掌握数据分析基础，涵盖 Excel、SQL、Python 数据处理',
    cover_url: '',
    category_id: 'cat-007',
    category_name: 'IT技术',
    sub_category: '数据分析',
    tags: ['数据', 'Excel', 'Python'],
    lecturer_id: 'LECT-202608-00007',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 5400,
    price: 19900,
    is_paid: true,
    lesson_count: 10,
    published_lesson_count: 10,
    camp_ref_count: 1,
    question_bank_id: 'QB-202608-00004',
    quiz_config_id: 'QUIZCFG-202608-00003',
    total_learners: 2103,
    total_learning_minutes: 56000,
    rating: 4.9,
    review_count: 187,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(20),
    completion_reward_enabled: true,
    answer_reward_enabled: true,
    reward_type: 'points',
    reward_amount: 50,
    red_packet_rule_id: null,
    created_at: dayAgo(30),
    updated_at: dayAgo(20),
  },
  {
    id: 'COURSE-202608-00006',
    course_no: 'COURSE-202608-00006',
    title: '短视频运营实战',
    orientation: 'portrait',
    description: '抖音/快手短视频账号从 0 到 1 运营全攻略，含脚本、剪辑、涨粉技巧',
    cover_url: '',
    category_id: 'cat-008',
    category_name: '新媒体运营',
    sub_category: '短视频',
    tags: ['短视频', '运营', '抖音'],
    lecturer_id: 'LECT-202608-00004',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 4200,
    price: 29900,
    is_paid: true,
    lesson_count: 8,
    published_lesson_count: 8,
    camp_ref_count: 2,
    question_bank_id: 'QB-202608-00005',
    quiz_config_id: null,
    total_learners: 3456,
    total_learning_minutes: 98000,
    rating: 4.7,
    review_count: 234,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(15),
    completion_reward_enabled: true,
    answer_reward_enabled: false,
    reward_type: 'red_packet_rule',
    reward_amount: 300,
    red_packet_rule_id: 'R-00003',
    created_at: dayAgo(25),
    updated_at: dayAgo(15),
  },
  {
    id: 'COURSE-202608-00007',
    course_no: 'COURSE-202608-00007',
    title: '直播带货实战课',
    description: '直播带货全流程实战：选品、话术、场控、复盘',
    cover_url: '',
    category_id: 'cat-008',
    category_name: '新媒体运营',
    sub_category: '直播带货',
    tags: ['直播', '带货', '电商'],
    lecturer_id: 'LECT-202608-00004',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'live',
    visibility: 'public',
    total_video_duration: 0,
    price: 39900,
    is_paid: true,
    lesson_count: 6,
    published_lesson_count: 6,
    camp_ref_count: 0,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 892,
    total_learning_minutes: 0,
    rating: 4.8,
    review_count: 67,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(8),
    completion_reward_enabled: false,
    answer_reward_enabled: false,
    reward_type: 'points',
    reward_amount: 0,
    red_packet_rule_id: null,
    created_at: dayAgo(12),
    updated_at: dayAgo(8),
  },
  {
    id: 'COURSE-202608-00008',
    course_no: 'COURSE-202608-00008',
    title: 'Python编程基础',
    description: '零基础入门 Python，涵盖语法、数据结构、函数、面向对象',
    cover_url: '',
    category_id: 'cat-007',
    category_name: 'IT技术',
    sub_category: '编程入门',
    tags: ['Python', '编程', '入门'],
    lecturer_id: 'LECT-202608-00007',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 7200,
    price: 0,
    is_paid: false,
    lesson_count: 12,
    published_lesson_count: 12,
    camp_ref_count: 1,
    question_bank_id: 'QB-202608-00006',
    quiz_config_id: 'QUIZCFG-202608-00004',
    total_learners: 5678,
    total_learning_minutes: 180000,
    rating: 4.9,
    review_count: 456,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(40),
    completion_reward_enabled: true,
    answer_reward_enabled: true,
    reward_type: 'points',
    reward_amount: 20,
    red_packet_rule_id: null,
    created_at: dayAgo(50),
    updated_at: dayAgo(40),
  },
  {
    id: 'COURSE-202608-00009',
    course_no: 'COURSE-202608-00009',
    title: '个人品牌打造',
    description: '从定位到变现，系统打造个人品牌',
    cover_url: '',
    category_id: 'cat-003',
    category_name: '职业技能',
    sub_category: '个人成长',
    tags: ['个人品牌', 'IP', '变现'],
    lecturer_id: 'LECT-202608-00005',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'camp_only',
    total_video_duration: 3000,
    price: 9900,
    is_paid: true,
    lesson_count: 6,
    published_lesson_count: 6,
    camp_ref_count: 1,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 445,
    total_learning_minutes: 12000,
    rating: 4.5,
    review_count: 34,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(6),
    completion_reward_enabled: false,
    answer_reward_enabled: true,
    reward_type: 'points',
    reward_amount: 15,
    red_packet_rule_id: null,
    created_at: dayAgo(10),
    updated_at: dayAgo(6),
  },
  {
    id: 'COURSE-202608-00010',
    course_no: 'COURSE-202608-00010',
    title: '财务自由入门',
    description: '理财基础知识，资产配置与复利的力量',
    cover_url: '',
    category_id: 'cat-006',
    category_name: '商业管理',
    sub_category: '理财入门',
    tags: ['理财', '投资', '复利'],
    lecturer_id: 'LECT-202608-00005',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 2400,
    price: 14900,
    is_paid: true,
    lesson_count: 5,
    published_lesson_count: 5,
    camp_ref_count: 0,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 678,
    total_learning_minutes: 18000,
    rating: 4.6,
    review_count: 45,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(18),
    completion_reward_enabled: true,
    answer_reward_enabled: false,
    reward_type: 'red_packet_rule',
    reward_amount: 150,
    red_packet_rule_id: 'R-00004',
    created_at: dayAgo(22),
    updated_at: dayAgo(18),
  },
  {
    id: 'COURSE-202608-00011',
    course_no: 'COURSE-202608-00011',
    title: '演讲表达力训练',
    description: '克服紧张、组织内容、掌控全场，系统提升演讲能力',
    cover_url: '',
    category_id: 'cat-003',
    category_name: '职业技能',
    sub_category: '表达能力',
    tags: ['演讲', '表达', '口才'],
    lecturer_id: 'LECT-202608-00002',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 3600,
    price: 0,
    is_paid: false,
    lesson_count: 7,
    published_lesson_count: 7,
    camp_ref_count: 0,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 1234,
    total_learning_minutes: 42000,
    rating: 4.7,
    review_count: 89,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(14),
    completion_reward_enabled: false,
    answer_reward_enabled: true,
    reward_type: 'points',
    reward_amount: 10,
    red_packet_rule_id: null,
    created_at: dayAgo(20),
    updated_at: dayAgo(14),
  },
  {
    id: 'COURSE-202608-00012',
    course_no: 'COURSE-202608-00012',
    title: 'AI工具实战应用',
    description: 'ChatGPT、Midjourney、Sora 等 AI 工具的实战应用指南',
    cover_url: '',
    category_id: 'cat-007',
    category_name: 'IT技术',
    sub_category: 'AI应用',
    tags: ['AI', 'ChatGPT', '效率'],
    lecturer_id: 'LECT-202608-00007',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'live',
    visibility: 'public',
    total_video_duration: 0,
    price: 49900,
    is_paid: true,
    lesson_count: 5,
    published_lesson_count: 5,
    camp_ref_count: 0,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 1567,
    total_learning_minutes: 0,
    rating: 4.9,
    review_count: 123,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(4),
    completion_reward_enabled: false,
    answer_reward_enabled: false,
    reward_type: 'points',
    reward_amount: 0,
    red_packet_rule_id: null,
    created_at: dayAgo(7),
    updated_at: dayAgo(4),
  },
  {
    id: 'COURSE-202608-00013',
    course_no: 'COURSE-202608-00013',
    title: '新媒体写作训练',
    description: '公众号、小红书、头条号新媒体写作方法与变现',
    cover_url: '',
    category_id: 'cat-008',
    category_name: '新媒体运营',
    sub_category: '内容创作',
    tags: ['写作', '新媒体', '变现'],
    lecturer_id: 'LECT-202608-00004',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 4800,
    price: 12900,
    is_paid: true,
    lesson_count: 9,
    published_lesson_count: 9,
    camp_ref_count: 1,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 2345,
    total_learning_minutes: 78000,
    rating: 4.6,
    review_count: 178,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(11),
    completion_reward_enabled: true,
    answer_reward_enabled: true,
    reward_type: 'points',
    reward_amount: 30,
    red_packet_rule_id: null,
    created_at: dayAgo(18),
    updated_at: dayAgo(11),
  },
  {
    id: 'COURSE-202608-00014',
    course_no: 'COURSE-202608-00014',
    title: '时间管理与效率提升',
    description: '番茄工作法、GTD、四象限法等时间管理工具实战',
    cover_url: '',
    category_id: 'cat-001',
    category_name: '通识教育',
    sub_category: '效率提升',
    tags: ['时间管理', '效率', 'GTD'],
    lecturer_id: 'LECT-202608-00001',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 2100,
    price: 0,
    is_paid: false,
    lesson_count: 4,
    published_lesson_count: 4,
    camp_ref_count: 0,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 3456,
    total_learning_minutes: 102000,
    rating: 4.8,
    review_count: 267,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(28),
    completion_reward_enabled: false,
    answer_reward_enabled: true,
    reward_type: 'points',
    reward_amount: 10,
    red_packet_rule_id: null,
    created_at: dayAgo(35),
    updated_at: dayAgo(28),
  },
  {
    id: 'COURSE-202608-00015',
    course_no: 'COURSE-202608-00015',
    title: '电商运营全攻略',
    description: '淘宝、拼多多、抖音电商运营方法论与案例拆解',
    cover_url: '',
    category_id: 'cat-006',
    category_name: '商业管理',
    sub_category: '电商运营',
    tags: ['电商', '运营', '淘宝'],
    lecturer_id: 'LECT-202608-00005',    lecturer_role_type: '资深讲师',
    source: 'upload',
    source_live_session_id: null,
    mode: 'recorded',
    visibility: 'public',
    total_video_duration: 6000,
    price: 39900,
    is_paid: true,
    lesson_count: 11,
    published_lesson_count: 11,
    camp_ref_count: 0,
    question_bank_id: null,
    quiz_config_id: null,
    total_learners: 1890,
    total_learning_minutes: 65000,
    rating: 4.7,
    review_count: 145,
    status: 'published',
    reviewer_id: 'admin-001',
    reviewed_at: dayAgo(9),
    completion_reward_enabled: true,
    answer_reward_enabled: false,
    reward_type: 'red_packet_rule',
    reward_amount: 250,
    red_packet_rule_id: 'R-00005',
    created_at: dayAgo(16),
    updated_at: dayAgo(9),
  },
];

// ── 课时（ENT-COURSE-002，多课程课时）──
export const SEED_LESSONS: Lesson[] = [
  // 课程1：高效学习方法论 5课时
  { id: 'LESSON-202608-00001', lesson_no: 'LESSON-202608-00001', course_id: 'COURSE-202608-00001', sort_order: 1, title: '学习方法概览', description: '高效学习的基本概念', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: true, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1234, avg_completion_rate: 0.92, avg_quiz_accuracy: 0.85, created_at: dayAgo(15), updated_at: dayAgo(10) },
  { id: 'LESSON-202608-00002', lesson_no: 'LESSON-202608-00002', course_id: 'COURSE-202608-00001', sort_order: 2, title: '工具使用技巧', description: '学习工具的高效使用方法', mode: 'recorded', video_url: '', video_duration: 540, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1100, avg_completion_rate: 0.88, avg_quiz_accuracy: 0.82, created_at: dayAgo(14), updated_at: dayAgo(10) },
  { id: 'LESSON-202608-00003', lesson_no: 'LESSON-202608-00003', course_id: 'COURSE-202608-00001', sort_order: 3, title: '时间管理', description: '时间管理的原则与方法', mode: 'recorded', video_url: '', video_duration: 480, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 980, avg_completion_rate: 0.85, avg_quiz_accuracy: 0.78, created_at: dayAgo(13), updated_at: dayAgo(10) },
  { id: 'LESSON-202608-00004', lesson_no: 'LESSON-202608-00004', course_id: 'COURSE-202608-00001', sort_order: 4, title: '专注力训练', description: '专注力的识别与训练方法', mode: 'recorded', video_url: '', video_duration: 540, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 890, avg_completion_rate: 0.90, avg_quiz_accuracy: 0.88, created_at: dayAgo(12), updated_at: dayAgo(10) },
  { id: 'LESSON-202608-00005', lesson_no: 'LESSON-202608-00005', course_id: 'COURSE-202608-00001', sort_order: 5, title: '笔记技巧', description: '高效笔记的注意事项', mode: 'recorded', video_url: '', video_duration: 540, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 850, avg_completion_rate: 0.87, avg_quiz_accuracy: 0.80, created_at: dayAgo(11), updated_at: dayAgo(10) },
  // 课程2：职场沟通技巧 3课时
  { id: 'LESSON-202608-00006', lesson_no: 'LESSON-202608-00006', course_id: 'COURSE-202608-00002', sort_order: 1, title: '沟通基础', description: '职场沟通的基本原则', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: true, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 567, avg_completion_rate: 0.91, avg_quiz_accuracy: 0.86, created_at: dayAgo(12), updated_at: dayAgo(7) },
  { id: 'LESSON-202608-00007', lesson_no: 'LESSON-202608-00007', course_id: 'COURSE-202608-00002', sort_order: 2, title: '科学表达', description: '如何清晰表达观点', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 500, avg_completion_rate: 0.88, avg_quiz_accuracy: 0.82, created_at: dayAgo(11), updated_at: dayAgo(7) },
  { id: 'LESSON-202608-00008', lesson_no: 'LESSON-202608-00008', course_id: 'COURSE-202608-00002', sort_order: 3, title: '高效协作', description: '团队协作技巧', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 480, avg_completion_rate: 0.85, avg_quiz_accuracy: 0.80, created_at: dayAgo(10), updated_at: dayAgo(7) },
  // 课程5：数据分析入门 10课时
  { id: 'LESSON-202608-00009', lesson_no: 'LESSON-202608-00009', course_id: 'COURSE-202608-00005', sort_order: 1, title: '数据分析概述', description: '数据分析的基本概念与流程', mode: 'recorded', video_url: '', video_duration: 540, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: true, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 2103, avg_completion_rate: 0.93, avg_quiz_accuracy: 0.88, created_at: dayAgo(30), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00010', lesson_no: 'LESSON-202608-00010', course_id: 'COURSE-202608-00005', sort_order: 2, title: 'Excel数据处理', description: 'Excel常用函数与数据透视表', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1980, avg_completion_rate: 0.89, avg_quiz_accuracy: 0.85, created_at: dayAgo(29), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00011', lesson_no: 'LESSON-202608-00011', course_id: 'COURSE-202608-00005', sort_order: 3, title: 'SQL基础', description: 'SQL查询与聚合', mode: 'recorded', video_url: '', video_duration: 720, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1850, avg_completion_rate: 0.85, avg_quiz_accuracy: 0.82, created_at: dayAgo(28), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00012', lesson_no: 'LESSON-202608-00012', course_id: 'COURSE-202608-00005', sort_order: 4, title: 'Python入门', description: 'Python基础语法', mode: 'recorded', video_url: '', video_duration: 660, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1750, avg_completion_rate: 0.87, avg_quiz_accuracy: 0.80, created_at: dayAgo(27), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00013', lesson_no: 'LESSON-202608-00013', course_id: 'COURSE-202608-00005', sort_order: 5, title: 'Pandas数据处理', description: 'Pandas库实战', mode: 'recorded', video_url: '', video_duration: 780, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1620, avg_completion_rate: 0.83, avg_quiz_accuracy: 0.78, created_at: dayAgo(26), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00014', lesson_no: 'LESSON-202608-00014', course_id: 'COURSE-202608-00005', sort_order: 6, title: '数据可视化', description: 'Matplotlib与Seaborn', mode: 'recorded', video_url: '', video_duration: 540, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1500, avg_completion_rate: 0.90, avg_quiz_accuracy: 0.85, created_at: dayAgo(25), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00015', lesson_no: 'LESSON-202608-00015', course_id: 'COURSE-202608-00005', sort_order: 7, title: '统计分析', description: '描述性统计与推断', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1380, avg_completion_rate: 0.81, avg_quiz_accuracy: 0.76, created_at: dayAgo(24), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00016', lesson_no: 'LESSON-202608-00016', course_id: 'COURSE-202608-00005', sort_order: 8, title: '数据建模', description: '回归与分类模型', mode: 'recorded', video_url: '', video_duration: 720, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1200, avg_completion_rate: 0.78, avg_quiz_accuracy: 0.72, created_at: dayAgo(23), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00017', lesson_no: 'LESSON-202608-00017', course_id: 'COURSE-202608-00005', sort_order: 9, title: '实战项目', description: '电商数据分析项目', mode: 'recorded', video_url: '', video_duration: 900, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 1100, avg_completion_rate: 0.85, avg_quiz_accuracy: 0.80, created_at: dayAgo(22), updated_at: dayAgo(20) },
  { id: 'LESSON-202608-00018', lesson_no: 'LESSON-202608-00018', course_id: 'COURSE-202608-00005', sort_order: 10, title: '面试技巧', description: '数据分析师面试指南', mode: 'recorded', video_url: '', video_duration: 360, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 980, avg_completion_rate: 0.92, avg_quiz_accuracy: 0.88, created_at: dayAgo(21), updated_at: dayAgo(20) },
  // 课程8：Python编程基础 12课时
  { id: 'LESSON-202608-00019', lesson_no: 'LESSON-202608-00019', course_id: 'COURSE-202608-00008', sort_order: 1, title: 'Python简介与安装', description: '环境搭建', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: true, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 5678, avg_completion_rate: 0.95, avg_quiz_accuracy: 0.90, created_at: dayAgo(50), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00020', lesson_no: 'LESSON-202608-00020', course_id: 'COURSE-202608-00008', sort_order: 2, title: '变量与数据类型', description: '基础语法', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 5400, avg_completion_rate: 0.92, avg_quiz_accuracy: 0.87, created_at: dayAgo(49), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00021', lesson_no: 'LESSON-202608-00021', course_id: 'COURSE-202608-00008', sort_order: 3, title: '条件与循环', description: '控制流', mode: 'recorded', video_url: '', video_duration: 720, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 5100, avg_completion_rate: 0.88, avg_quiz_accuracy: 0.83, created_at: dayAgo(48), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00022', lesson_no: 'LESSON-202608-00022', course_id: 'COURSE-202608-00008', sort_order: 4, title: '函数与模块', description: '函数定义与调用', mode: 'recorded', video_url: '', video_duration: 660, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 4800, avg_completion_rate: 0.85, avg_quiz_accuracy: 0.80, created_at: dayAgo(47), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00023', lesson_no: 'LESSON-202608-00023', course_id: 'COURSE-202608-00008', sort_order: 5, title: '列表与字典', description: '数据结构', mode: 'recorded', video_url: '', video_duration: 720, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 4500, avg_completion_rate: 0.83, avg_quiz_accuracy: 0.78, created_at: dayAgo(46), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00024', lesson_no: 'LESSON-202608-00024', course_id: 'COURSE-202608-00008', sort_order: 6, title: '面向对象基础', description: '类与对象', mode: 'recorded', video_url: '', video_duration: 780, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 4200, avg_completion_rate: 0.80, avg_quiz_accuracy: 0.74, created_at: dayAgo(45), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00025', lesson_no: 'LESSON-202608-00025', course_id: 'COURSE-202608-00008', sort_order: 7, title: '文件操作', description: '读写文件', mode: 'recorded', video_url: '', video_duration: 540, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 3900, avg_completion_rate: 0.86, avg_quiz_accuracy: 0.82, created_at: dayAgo(44), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00026', lesson_no: 'LESSON-202608-00026', course_id: 'COURSE-202608-00008', sort_order: 8, title: '异常处理', description: 'try/except', mode: 'recorded', video_url: '', video_duration: 480, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 3600, avg_completion_rate: 0.84, avg_quiz_accuracy: 0.80, created_at: dayAgo(43), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00027', lesson_no: 'LESSON-202608-00027', course_id: 'COURSE-202608-00008', sort_order: 9, title: '装饰器与生成器', description: '高级特性', mode: 'recorded', video_url: '', video_duration: 660, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 3000, avg_completion_rate: 0.76, avg_quiz_accuracy: 0.70, created_at: dayAgo(42), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00028', lesson_no: 'LESSON-202608-00028', course_id: 'COURSE-202608-00008', sort_order: 10, title: '网络请求', description: 'requests库', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 2700, avg_completion_rate: 0.82, avg_quiz_accuracy: 0.77, created_at: dayAgo(41), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00029', lesson_no: 'LESSON-202608-00029', course_id: 'COURSE-202608-00008', sort_order: 11, title: '爬虫入门', description: 'BeautifulSoup', mode: 'recorded', video_url: '', video_duration: 720, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 2400, avg_completion_rate: 0.79, avg_quiz_accuracy: 0.73, created_at: dayAgo(41), updated_at: dayAgo(40) },
  { id: 'LESSON-202608-00030', lesson_no: 'LESSON-202608-00030', course_id: 'COURSE-202608-00008', sort_order: 12, title: '综合项目', description: 'Web爬虫项目实战', mode: 'recorded', video_url: '', video_duration: 900, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 2100, avg_completion_rate: 0.85, avg_quiz_accuracy: 0.80, created_at: dayAgo(40), updated_at: dayAgo(40) },
  // 课程6：短视频运营 3课时（部分）
  { id: 'LESSON-202608-00031', lesson_no: 'LESSON-202608-00031', course_id: 'COURSE-202608-00006', sort_order: 1, title: '账号定位', description: '如何找到你的细分赛道', mode: 'recorded', video_url: '', video_duration: 540, orientation: 'portrait', live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: true, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 3456, avg_completion_rate: 0.91, avg_quiz_accuracy: 0.85, created_at: dayAgo(25), updated_at: dayAgo(15) },
  { id: 'LESSON-202608-00032', lesson_no: 'LESSON-202608-00032', course_id: 'COURSE-202608-00006', sort_order: 2, title: '脚本创作', description: '爆款脚本的写作公式', mode: 'recorded', video_url: '', video_duration: 600, orientation: 'portrait', live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 3200, avg_completion_rate: 0.88, avg_quiz_accuracy: 0.82, created_at: dayAgo(24), updated_at: dayAgo(15) },
  { id: 'LESSON-202608-00033', lesson_no: 'LESSON-202608-00033', course_id: 'COURSE-202608-00006', sort_order: 3, title: '剪辑技巧', description: '剪映/Pr 快速上手', mode: 'recorded', video_url: '', video_duration: 720, orientation: 'portrait', live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'manual', source_camp_id: null, source_camp_title: null, source_schedule_id: null, total_learners: 2950, avg_completion_rate: 0.85, avg_quiz_accuracy: 0.78, created_at: dayAgo(23), updated_at: dayAgo(15) },
  // 营期排课生成的课时（source=camp_schedule）
  { id: 'LESSON-202608-00034', lesson_no: 'LESSON-202608-00034', course_id: 'COURSE-202608-00001', sort_order: 6, title: '营期Day1·开营导学', description: '营期排课生成', mode: 'recorded', video_url: '', video_duration: 600, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'camp_schedule', source_camp_id: 'CAMP-202608-00001', source_camp_title: '高效学习7天营', source_schedule_id: 'SCH-001', total_learners: 200, avg_completion_rate: 0.95, avg_quiz_accuracy: 0.90, created_at: dayAgo(5), updated_at: dayAgo(5) },
  { id: 'LESSON-202608-00035', lesson_no: 'LESSON-202608-00035', course_id: 'COURSE-202608-00005', sort_order: 11, title: '营期Day2·数据清洗实战', description: '营期排课生成', mode: 'recorded', video_url: '', video_duration: 720, live_session_id: null, question_bank_id: null, status: 'published', is_free_preview: false, source: 'camp_schedule', source_camp_id: 'CAMP-202608-00002', source_camp_title: '数据分析21天营', source_schedule_id: 'SCH-002', total_learners: 150, avg_completion_rate: 0.90, avg_quiz_accuracy: 0.85, created_at: dayAgo(4), updated_at: dayAgo(4) },
];

// ── 题库（ENT-COURSE-003，6个·1对1绑定课程）──
export const SEED_QUESTION_BANKS: QuestionBank[] = [
  { id: 'QB-202608-00001', bank_no: 'QB-202608-00001', course_id: 'COURSE-202608-00001', lesson_id: null, title: '学习方法题库', description: '高效学习方法相关题目', question_count: 8, total_answer_count: 4500, avg_accuracy: 0.82, creator_id: 'LECT-202608-00001', creator_role: 'main_lecturer', status: 'published', created_at: dayAgo(14), updated_at: dayAgo(10) },
  { id: 'QB-202608-00002', bank_no: 'QB-202608-00002', course_id: 'COURSE-202608-00002', lesson_id: null, title: '职场沟通题库', description: '职场沟通相关题目', question_count: 5, total_answer_count: 1200, avg_accuracy: 0.85, creator_id: 'LECT-202608-00002', creator_role: 'main_lecturer', status: 'published', created_at: dayAgo(11), updated_at: dayAgo(7) },
  { id: 'QB-202608-00003', bank_no: 'QB-202608-00003', course_id: 'COURSE-202608-00003', lesson_id: null, title: '运动健康题库', description: '运动健康相关题目', question_count: 6, total_answer_count: 320, avg_accuracy: 0.78, creator_id: 'LECT-202608-00001', creator_role: 'main_lecturer', status: 'published', created_at: dayAgo(7), updated_at: dayAgo(5) },
  { id: 'QB-202608-00004', bank_no: 'QB-202608-00004', course_id: 'COURSE-202608-00005', lesson_id: null, title: '数据分析题库', description: '数据分析入门相关题目', question_count: 10, total_answer_count: 8900, avg_accuracy: 0.80, creator_id: 'LECT-202608-00007', creator_role: 'main_lecturer', status: 'published', created_at: dayAgo(28), updated_at: dayAgo(20) },
  { id: 'QB-202608-00005', bank_no: 'QB-202608-00005', course_id: 'COURSE-202608-00006', lesson_id: null, title: '短视频运营题库', description: '短视频运营相关题目', question_count: 7, total_answer_count: 5600, avg_accuracy: 0.83, creator_id: 'LECT-202608-00004', creator_role: 'main_lecturer', status: 'published', created_at: dayAgo(24), updated_at: dayAgo(15) },
  { id: 'QB-202608-00006', bank_no: 'QB-202608-00006', course_id: 'COURSE-202608-00008', lesson_id: null, title: 'Python编程题库', description: 'Python编程基础相关题目', question_count: 12, total_answer_count: 12000, avg_accuracy: 0.81, creator_id: 'LECT-202608-00007', creator_role: 'main_lecturer', status: 'published', created_at: dayAgo(48), updated_at: dayAgo(40) },
];

// ── 题目（ENT-COURSE-004，多题库·每题独立trigger_threshold·BR-QUIZ-003）──
export const SEED_QUESTIONS: Question[] = [
  // QB-1 学习方法题库 8题
  { id: 'QUEST-202608-00001', question_no: 'QUEST-202608-00001', bank_id: 'QB-202608-00001', sort_order: 1, question_type: 'single', content: '番茄工作法的一个番茄钟是多少分钟？', image_url: '', options: [{ key: 'A', content: '25分钟' }, { key: 'B', content: '45分钟' }, { key: 'C', content: '60分钟' }], correct_answer: ['A'], explanation: '番茄工作法标准番茄钟为25分钟专注+5分钟休息', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 1234, correct_count: 1023, accuracy_rate: 0.83, created_at: dayAgo(14), updated_at: dayAgo(10) },
  { id: 'QUEST-202608-00002', question_no: 'QUEST-202608-00002', bank_id: 'QB-202608-00001', sort_order: 2, question_type: 'single', content: '康奈尔笔记法将页面分为几栏？', image_url: '', options: [{ key: 'A', content: '2栏' }, { key: 'B', content: '3栏' }, { key: 'C', content: '4栏' }], correct_answer: ['B'], explanation: '康奈尔笔记法将页面分为线索栏、笔记栏、总结栏3栏', score: 1, trigger_type: 'inline_at_time', trigger_time: 300, trigger_threshold: 0.8, total_answer_count: 1100, correct_count: 924, accuracy_rate: 0.84, created_at: dayAgo(14), updated_at: dayAgo(10) },
  { id: 'QUEST-202608-00003', question_no: 'QUEST-202608-00003', bank_id: 'QB-202608-00001', sort_order: 3, question_type: 'multiple', content: '以下哪些是高效学习的方法？', image_url: '', options: [{ key: 'A', content: '主动回忆' }, { key: 'B', content: '间隔重复' }, { key: 'C', content: '费曼技巧' }, { key: 'D', content: '死记硬背' }], correct_answer: ['A', 'B', 'C'], explanation: '主动回忆、间隔重复、费曼技巧均为科学学习方法', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 890, correct_count: 712, accuracy_rate: 0.80, created_at: dayAgo(13), updated_at: dayAgo(10) },
  { id: 'QUEST-202608-00004', question_no: 'QUEST-202608-00004', bank_id: 'QB-202608-00001', sort_order: 4, question_type: 'single', content: 'GTD时间管理法的全称是？', image_url: '', options: [{ key: 'A', content: 'Getting Things Done' }, { key: 'B', content: 'Go To Do' }, { key: 'C', content: 'Good Time Day' }], correct_answer: ['A'], explanation: 'GTD全称 Getting Things Done，David Allen 提出', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 780, correct_count: 650, accuracy_rate: 0.83, created_at: dayAgo(12), updated_at: dayAgo(10) },
  { id: 'QUEST-202608-00005', question_no: 'QUEST-202608-00005', bank_id: 'QB-202608-00001', sort_order: 5, question_type: 'multiple', content: '以下哪些属于时间管理工具？', image_url: '', options: [{ key: 'A', content: '番茄工作法' }, { key: 'B', content: '四象限法' }, { key: 'C', content: 'GTD' }, { key: 'D', content: '刷短视频' }], correct_answer: ['A', 'B', 'C'], explanation: '番茄/四象限/GTD都是经典时间管理工具', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 680, correct_count: 540, accuracy_rate: 0.79, created_at: dayAgo(12), updated_at: dayAgo(10) },
  { id: 'QUEST-202608-00006', question_no: 'QUEST-202608-00006', bank_id: 'QB-202608-00001', sort_order: 6, question_type: 'single', content: '费曼技巧的核心是？', image_url: '', options: [{ key: 'A', content: '用简单语言教会别人' }, { key: 'B', content: '多做笔记' }, { key: 'C', content: '大量刷题' }], correct_answer: ['A'], explanation: '费曼技巧核心是用最简单语言把概念讲明白', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 560, correct_count: 470, accuracy_rate: 0.84, created_at: dayAgo(11), updated_at: dayAgo(10) },
  { id: 'QUEST-202608-00007', question_no: 'QUEST-202608-00007', bank_id: 'QB-202608-00001', sort_order: 7, question_type: 'single', content: '艾宾浩斯遗忘曲线描述的是？', image_url: '', options: [{ key: 'A', content: '记忆随时间衰减规律' }, { key: 'B', content: '学习效率曲线' }, { key: 'C', content: '注意力变化' }], correct_answer: ['A'], explanation: '艾宾浩斯遗忘曲线描述记忆随时间衰减的规律', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 450, correct_count: 380, accuracy_rate: 0.84, created_at: dayAgo(11), updated_at: dayAgo(10) },
  { id: 'QUEST-202608-00008', question_no: 'QUEST-202608-00008', bank_id: 'QB-202608-00001', sort_order: 8, question_type: 'multiple', content: '科学笔记法的要素包括？', image_url: '', options: [{ key: 'A', content: '记录' }, { key: 'B', content: '简化' }, { key: 'C', content: '背诵' }, { key: 'D', content: '反思' }], correct_answer: ['A', 'B', 'C', 'D'], explanation: 'SQ3R笔记法包括 Survey/Question/Read/Recite/Review', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 320, correct_count: 220, accuracy_rate: 0.69, created_at: dayAgo(10), updated_at: dayAgo(10) },
  // QB-2 职场沟通题库 5题
  { id: 'QUEST-202608-00009', question_no: 'QUEST-202608-00009', bank_id: 'QB-202608-00002', sort_order: 1, question_type: 'single', content: '非暴力沟通的四个要素是？', image_url: '', options: [{ key: 'A', content: '观察/感受/需要/请求' }, { key: 'B', content: '听/说/读/写' }, { key: 'C', content: '想/做/说/看' }], correct_answer: ['A'], explanation: '非暴力沟通四要素：观察、感受、需要、请求', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 567, correct_count: 480, accuracy_rate: 0.85, created_at: dayAgo(11), updated_at: dayAgo(7) },
  { id: 'QUEST-202608-00010', question_no: 'QUEST-202608-00010', bank_id: 'QB-202608-00002', sort_order: 2, question_type: 'multiple', content: '以下哪些是有效沟通的原则？', image_url: '', options: [{ key: 'A', content: '清晰' }, { key: 'B', content: '简洁' }, { key: 'C', content: '具体' }, { key: 'D', content: '含糊' }], correct_answer: ['A', 'B', 'C'], explanation: '有效沟通原则：清晰、简洁、具体、礼貌', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 480, correct_count: 400, accuracy_rate: 0.83, created_at: dayAgo(10), updated_at: dayAgo(7) },
  { id: 'QUEST-202608-00011', question_no: 'QUEST-202608-00011', bank_id: 'QB-202608-00002', sort_order: 3, question_type: 'single', content: '"我信息"表达法的结构是？', image_url: '', options: [{ key: 'A', content: '行为+感受+影响' }, { key: 'B', content: '批评+指责+要求' }, { key: 'C', content: '观察+评价+建议' }], correct_answer: ['A'], explanation: '我信息：描述行为+表达感受+说明影响', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 400, correct_count: 320, accuracy_rate: 0.80, created_at: dayAgo(9), updated_at: dayAgo(7) },
  { id: 'QUEST-202608-00012', question_no: 'QUEST-202608-00012', bank_id: 'QB-202608-00002', sort_order: 4, question_type: 'single', content: '积极倾听的核心是？', image_url: '', options: [{ key: 'A', content: '专注+理解+回应' }, { key: 'B', content: '多说多讲' }, { key: 'C', content: '打断对方' }], correct_answer: ['A'], explanation: '积极倾听=专注+理解+适当回应', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 350, correct_count: 280, accuracy_rate: 0.80, created_at: dayAgo(8), updated_at: dayAgo(7) },
  { id: 'QUEST-202608-00013', question_no: 'QUEST-202608-00013', bank_id: 'QB-202608-00002', sort_order: 5, question_type: 'multiple', content: '处理职场冲突的方法包括？', image_url: '', options: [{ key: 'A', content: '直接沟通' }, { key: 'B', content: '换位思考' }, { key: 'C', content: '寻求调解' }, { key: 'D', content: '冷战回避' }], correct_answer: ['A', 'B', 'C'], explanation: '冲突处理：直接沟通、换位思考、必要时寻求调解', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 280, correct_count: 210, accuracy_rate: 0.75, created_at: dayAgo(7), updated_at: dayAgo(7) },
  // QB-4 数据分析题库 10题
  { id: 'QUEST-202608-00014', question_no: 'QUEST-202608-00014', bank_id: 'QB-202608-00004', sort_order: 1, question_type: 'single', content: '数据分析的基本流程是？', image_url: '', options: [{ key: 'A', content: '采集→清洗→分析→可视化' }, { key: 'B', content: '看→想→做' }, { key: 'C', content: '问→答→完' }], correct_answer: ['A'], explanation: '数据分析流程：数据采集、清洗、分析、可视化', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 2103, correct_count: 1850, accuracy_rate: 0.88, created_at: dayAgo(28), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00015', question_no: 'QUEST-202608-00015', bank_id: 'QB-202608-00004', sort_order: 2, question_type: 'single', content: 'Excel 中实现数据透视的功能是？', image_url: '', options: [{ key: 'A', content: '数据透视表' }, { key: 'B', content: '条件格式' }, { key: 'C', content: '排序' }], correct_answer: ['A'], explanation: '数据透视表是Excel最强大的汇总分析工具', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 1980, correct_count: 1750, accuracy_rate: 0.88, created_at: dayAgo(27), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00016', question_no: 'QUEST-202608-00016', bank_id: 'QB-202608-00004', sort_order: 3, question_type: 'single', content: 'SQL 中用于查询的关键字是？', image_url: '', options: [{ key: 'A', content: 'SELECT' }, { key: 'B', content: 'UPDATE' }, { key: 'C', content: 'DELETE' }], correct_answer: ['A'], explanation: 'SELECT 用于查询数据', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 1850, correct_count: 1700, accuracy_rate: 0.92, created_at: dayAgo(26), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00017', question_no: 'QUEST-202608-00017', bank_id: 'QB-202608-00004', sort_order: 4, question_type: 'multiple', content: '以下哪些是 Python 数据分析库？', image_url: '', options: [{ key: 'A', content: 'Pandas' }, { key: 'B', content: 'NumPy' }, { key: 'C', content: 'Matplotlib' }, { key: 'D', content: 'Photoshop' }], correct_answer: ['A', 'B', 'C'], explanation: 'Pandas/NumPy/Matplotlib 是 Python 数据分析三剑客', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 1750, correct_count: 1500, accuracy_rate: 0.86, created_at: dayAgo(25), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00018', question_no: 'QUEST-202608-00018', bank_id: 'QB-202608-00004', sort_order: 5, question_type: 'single', content: 'Pandas 中用于缺失值处理的函数是？', image_url: '', options: [{ key: 'A', content: 'fillna' }, { key: 'B', content: 'groupby' }, { key: 'C', content: 'merge' }], correct_answer: ['A'], explanation: 'fillna 用于填充缺失值', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 1620, correct_count: 1380, accuracy_rate: 0.85, created_at: dayAgo(24), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00019', question_no: 'QUEST-202608-00019', bank_id: 'QB-202608-00004', sort_order: 6, question_type: 'single', content: '描述性统计不包括？', image_url: '', options: [{ key: 'A', content: '均值' }, { key: 'B', content: '方差' }, { key: 'C', content: '假设检验' }], correct_answer: ['C'], explanation: '假设检验属于推断统计', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.8, total_answer_count: 1500, correct_count: 1200, accuracy_rate: 0.80, created_at: dayAgo(23), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00020', question_no: 'QUEST-202608-00020', bank_id: 'QB-202608-00004', sort_order: 7, question_type: 'multiple', content: '常见的数据可视化图表有？', image_url: '', options: [{ key: 'A', content: '柱状图' }, { key: 'B', content: '折线图' }, { key: 'C', content: '散点图' }, { key: 'D', content: '饼图' }], correct_answer: ['A', 'B', 'C', 'D'], explanation: '柱/折/散/饼都是常见可视化图表', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 1380, correct_count: 1200, accuracy_rate: 0.87, created_at: dayAgo(22), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00021', question_no: 'QUEST-202608-00021', bank_id: 'QB-202608-00004', sort_order: 8, question_type: 'single', content: '线性回归用于解决什么问题？', image_url: '', options: [{ key: 'A', content: '连续值预测' }, { key: 'B', content: '分类' }, { key: 'C', content: '聚类' }], correct_answer: ['A'], explanation: '线性回归用于连续值预测', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 1200, correct_count: 980, accuracy_rate: 0.82, created_at: dayAgo(21), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00022', question_no: 'QUEST-202608-00022', bank_id: 'QB-202608-00004', sort_order: 9, question_type: 'single', content: '决策树属于哪类算法？', image_url: '', options: [{ key: 'A', content: '监督学习' }, { key: 'B', content: '无监督学习' }, { key: 'C', content: '强化学习' }], correct_answer: ['A'], explanation: '决策树是有标签训练，属监督学习', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.8, total_answer_count: 1100, correct_count: 880, accuracy_rate: 0.80, created_at: dayAgo(20), updated_at: dayAgo(20) },
  { id: 'QUEST-202608-00023', question_no: 'QUEST-202608-00023', bank_id: 'QB-202608-00004', sort_order: 10, question_type: 'multiple', content: '数据清洗的常见操作包括？', image_url: '', options: [{ key: 'A', content: '去重' }, { key: 'B', content: '缺失值处理' }, { key: 'C', content: '异常值处理' }, { key: 'D', content: '格式统一' }], correct_answer: ['A', 'B', 'C', 'D'], explanation: '数据清洗包含去重/缺失/异常/格式', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 980, correct_count: 780, accuracy_rate: 0.80, created_at: dayAgo(20), updated_at: dayAgo(20) },
  // QB-5 短视频运营题库 7题
  { id: 'QUEST-202608-00024', question_no: 'QUEST-202608-00024', bank_id: 'QB-202608-00005', sort_order: 1, question_type: 'single', content: '抖音推荐算法的核心指标是？', image_url: '', options: [{ key: 'A', content: '完播率' }, { key: 'B', content: '视频时长' }, { key: 'C', content: '发布时间' }], correct_answer: ['A'], explanation: '完播率是抖音推荐的核心指标', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 3456, correct_count: 3000, accuracy_rate: 0.87, created_at: dayAgo(24), updated_at: dayAgo(15) },
  { id: 'QUEST-202608-00025', question_no: 'QUEST-202608-00025', bank_id: 'QB-202608-00005', sort_order: 2, question_type: 'multiple', content: '短视频选题的方法有？', image_url: '', options: [{ key: 'A', content: '热点追踪' }, { key: 'B', content: '痛点切入' }, { key: 'C', content: '差异化定位' }, { key: 'D', content: '抄袭搬运' }], correct_answer: ['A', 'B', 'C'], explanation: '选题方法：追热点、切痛点、差异化', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 3200, correct_count: 2700, accuracy_rate: 0.84, created_at: dayAgo(23), updated_at: dayAgo(15) },
  { id: 'QUEST-202608-00026', question_no: 'QUEST-202608-00026', bank_id: 'QB-202608-00005', sort_order: 3, question_type: 'single', content: '爆款短视频的开头黄金时间是？', image_url: '', options: [{ key: 'A', content: '前3秒' }, { key: 'B', content: '前30秒' }, { key: 'C', content: '前1分钟' }], correct_answer: ['A'], explanation: '前3秒决定用户是否继续看', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 2950, correct_count: 2600, accuracy_rate: 0.88, created_at: dayAgo(22), updated_at: dayAgo(15) },
  { id: 'QUEST-202608-00027', question_no: 'QUEST-202608-00027', bank_id: 'QB-202608-00005', sort_order: 4, question_type: 'single', content: '以下哪种内容更容易涨粉？', image_url: '', options: [{ key: 'A', content: '垂直领域持续输出' }, { key: 'B', content: '什么都发' }, { key: 'C', content: '偶尔更新' }], correct_answer: ['A'], explanation: '垂直持续输出是涨粉关键', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 2700, correct_count: 2400, accuracy_rate: 0.89, created_at: dayAgo(21), updated_at: dayAgo(15) },
  { id: 'QUEST-202608-00028', question_no: 'QUEST-202608-00028', bank_id: 'QB-202608-00005', sort_order: 5, question_type: 'multiple', content: '短视频变现方式有？', image_url: '', options: [{ key: 'A', content: '带货' }, { key: 'B', content: '广告' }, { key: 'C', content: '知识付费' }, { key: 'D', content: '直播打赏' }], correct_answer: ['A', 'B', 'C', 'D'], explanation: '带货/广告/知识付费/直播打赏都是变现方式', score: 2, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9, total_answer_count: 2500, correct_count: 2200, accuracy_rate: 0.88, created_at: dayAgo(20), updated_at: dayAgo(15) },
  { id: 'QUEST-202608-00029', question_no: 'QUEST-202608-00029', bank_id: 'QB-202608-00005', sort_order: 6, question_type: 'single', content: '短视频发布最佳时间通常是？', image_url: '', options: [{ key: 'A', content: '晚 8-10 点' }, { key: 'B', content: '凌晨 3 点' }, { key: 'C', content: '上午 6 点' }], correct_answer: ['A'], explanation: '晚 8-10 点用户活跃度最高', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.8, total_answer_count: 2300, correct_count: 1950, accuracy_rate: 0.85, created_at: dayAgo(18), updated_at: dayAgo(15) },
  { id: 'QUEST-202608-00030', question_no: 'QUEST-202608-00030', bank_id: 'QB-202608-00005', sort_order: 7, question_type: 'single', content: '短视频脚本的核心结构是？', image_url: '', options: [{ key: 'A', content: '钩子+内容+引导' }, { key: 'B', content: '随便讲' }, { key: 'C', content: '只讲卖点' }], correct_answer: ['A'], explanation: '钩子吸引+内容输出+引导互动', score: 1, trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.85, total_answer_count: 2100, correct_count: 1800, accuracy_rate: 0.86, created_at: dayAgo(16), updated_at: dayAgo(15) },
];

// ── 答题配置（ENT-COURSE-006）──
export const SEED_QUIZ_CONFIGS: CourseQuizConfig[] = [
  { id: 'QUIZCFG-202608-00001', course_id: 'COURSE-202608-00001', bank_id: 'QB-202608-00001', enabled: true, pass_rate: 0.6, question_configs: [{ question_id: 'QUEST-202608-00001', trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9 }, { question_id: 'QUEST-202608-00002', trigger_type: 'inline_at_time', trigger_time: 300, trigger_threshold: 0.8 }, { question_id: 'QUEST-202608-00003', trigger_type: 'inline_at_completion', trigger_time: undefined, trigger_threshold: 0.9 }], final_quiz_enabled: false, final_quiz_question_count: 20, final_quiz_pass_rate: 0.6, created_at: dayAgo(14), updated_at: dayAgo(10) },
];

// ── 课程评价（ENT-COURSE-007·BR-COURSE-009模糊回显）──
export const SEED_REVIEWS: CourseReview[] = [
  { id: 'REVIEW-202608-00001', course_id: 'COURSE-202608-00001', camp_id: null, student_id: 'STU-001', student_name: '王五', student_avatar: '', rating: 5, content: '课程不错，加我微信 study2026 领取学习资料包', images: [], review_status: 'rejected', reviewer_id: 'admin-001', review_remark: '内容包含联系方式，禁止站外引流，请删除后重新提交', reviewed_at: dayAgo(1), reply_count: 0, like_count: 0, is_hidden: false, created_at: dayAgo(10), updated_at: dayAgo(1) },
  { id: 'REVIEW-202608-00002', course_id: 'COURSE-202608-00001', camp_id: null, student_id: 'STU-002', student_name: '赵六', student_avatar: '', rating: 4, content: '内容不错，希望多一些实操', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(8), reply_count: 0, like_count: 5, is_hidden: false, created_at: dayAgo(9), updated_at: dayAgo(8) },
  { id: 'REVIEW-202608-00003', course_id: 'COURSE-202608-00001', camp_id: null, student_id: 'STU-003', student_name: '钱七', student_avatar: '', rating: 3, content: '（审核中内容·模糊回显）', images: [], review_status: 'pending', reviewer_id: null, review_remark: undefined, reviewed_at: null, reply_count: 0, like_count: 0, is_hidden: false, created_at: dayAgo(1), updated_at: dayAgo(1) },
  { id: 'REVIEW-202608-00004', course_id: 'COURSE-202608-00005', camp_id: null, student_id: 'STU-004', student_name: '孙八', student_avatar: '', rating: 5, content: '数据分析课程讲得很透彻，Pandas部分尤其精彩', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(18), reply_count: 1, like_count: 45, is_hidden: false, created_at: dayAgo(19), updated_at: dayAgo(18) },
  { id: 'REVIEW-202608-00005', course_id: 'COURSE-202608-00005', camp_id: null, student_id: 'STU-005', student_name: '周九', student_avatar: '', rating: 4, content: '内容很扎实，SQL部分可以再深入一些', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(17), reply_count: 0, like_count: 12, is_hidden: false, created_at: dayAgo(18), updated_at: dayAgo(17) },
  { id: 'REVIEW-202608-00006', course_id: 'COURSE-202608-00005', camp_id: null, student_id: 'STU-006', student_name: '吴十', student_avatar: '', rating: 5, content: '从零基础到能做项目，进步非常大', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(16), reply_count: 2, like_count: 38, is_hidden: false, created_at: dayAgo(17), updated_at: dayAgo(16) },
  { id: 'REVIEW-202608-00007', course_id: 'COURSE-202608-00006', camp_id: null, student_id: 'STU-007', student_name: '郑十一', student_avatar: '', rating: 5, content: '短视频课讲得超级实用，账号涨粉明显', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(13), reply_count: 1, like_count: 67, is_hidden: false, created_at: dayAgo(14), updated_at: dayAgo(13) },
  { id: 'REVIEW-202608-00008', course_id: 'COURSE-202608-00006', camp_id: null, student_id: 'STU-008', student_name: '王十二', student_avatar: '', rating: 4, content: '剪辑部分很详细，脚本可以再多一些案例', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(12), reply_count: 0, like_count: 23, is_hidden: false, created_at: dayAgo(13), updated_at: dayAgo(12) },
  { id: 'REVIEW-202608-00009', course_id: 'COURSE-202608-00008', camp_id: null, student_id: 'STU-009', student_name: '李十三', student_avatar: '', rating: 5, content: 'Python入门首选，讲得非常清楚', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(38), reply_count: 3, like_count: 156, is_hidden: false, created_at: dayAgo(39), updated_at: dayAgo(38) },
  { id: 'REVIEW-202608-00010', course_id: 'COURSE-202608-00008', camp_id: null, student_id: 'STU-010', student_name: '张十四', student_avatar: '', rating: 4, content: '面向对象那节有点难，其他都很好', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(37), reply_count: 1, like_count: 45, is_hidden: false, created_at: dayAgo(38), updated_at: dayAgo(37) },
  { id: 'REVIEW-202608-00011', course_id: 'COURSE-202608-00008', camp_id: null, student_id: 'STU-011', student_name: '陈十五', student_avatar: '', rating: 5, content: '爬虫实战项目受益匪浅', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(36), reply_count: 0, like_count: 78, is_hidden: false, created_at: dayAgo(37), updated_at: dayAgo(36) },
  { id: 'REVIEW-202608-00012', course_id: 'COURSE-202608-00002', camp_id: null, student_id: 'STU-012', student_name: '林十六', student_avatar: '', rating: 4, content: '沟通技巧很实用，工作中有改善', images: [], review_status: 'approved', reviewer_id: 'admin-001', review_remark: undefined, reviewed_at: dayAgo(5), reply_count: 0, like_count: 8, is_hidden: false, created_at: dayAgo(6), updated_at: dayAgo(5) },
];

// ── 评价回复（ENT-COURSE-008）──
export const SEED_REVIEW_REPLIES: CourseReviewReply[] = [
  { id: 'REPLY-202608-00001', review_id: 'REVIEW-202608-00001', replier_id: 'LECT-202608-00001', replier_name: '张三', replier_role: 'main_lecturer', content: '感谢评价！实操内容后续会补充', parent_reply_id: null, review_status: 'approved', created_at: dayAgo(9), updated_at: dayAgo(9) },
  { id: 'REPLY-202608-00002', review_id: 'REVIEW-202608-00001', replier_id: 'STU-001', replier_name: '王五', replier_role: 'student', content: '期待更新！', parent_reply_id: 'REPLY-202608-00001', review_status: 'approved', created_at: dayAgo(8), updated_at: dayAgo(8) },
];

// ── 答题记录（ENT-COURSE-005·D18不分区source_type标记）──
export const SEED_ANSWER_RECORDS: AnswerRecord[] = [
  { id: 'ANSWER-202608-00001', student_id: 'STU-001', camp_id: 'CAMP-202608-00001', course_id: 'COURSE-202608-00001', lesson_id: 'LESSON-202608-00001', question_id: 'QUEST-202608-00001', bank_id: 'QB-202608-00001', student_answer: ['A'], is_correct: true, score: 1, duration_seconds: 30, video_progress_at_answer: 540, completion_rate_at_answer: 0.9, source_type: 'camp', created_at: dayAgo(5) },
];
